# Change these first
owner: wouterplanet # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Wouter Planet
    url: https://www.wouterplanet.com
  - name: Merch Site
    url: https://merch.wouterplanet.com
  - name: Blog
    url: https://blog.wouterplanet.com
  - name: API
    url: https://api.wouterplanet.com/ping
  - name: CDN
    url: https://cdn.wouterplanet.com
  - name: CDN 4
    url: https://cdn4.wouterplanet.com
  - name: CDN Orange
    url: $URL_CNDORANGE
  - name: Administration
    url: $URL_ADMINISTRATION
  - name: Fun Delivery Service
    url: $URL_FUN
  - name: NAS
    url: https://nas.wouterplanet.com
    
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
  
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wouter Planet - Upptime
  customHeadHtml: "<meta http-equiv='refresh' content='600' />"
  baseUrl: /monitoring
  introTitle: "Status page for **Wouter Planet** and related services."
  introMessage: Uses Github actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
